yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech')

]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.post_create, name='post_create'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts'))
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import mimetypes

    import debug_toolbar

    mimetypes.add_type("application/javascript", ".js", True)
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/article.html
{% load thumbnail %}
<article>
  <ul>
    {% if show_author %}
      <li>
        Автор: <a href="{% url 'posts:profile' post.author.username %}"> {{ post.author.get_full_name }} </a>
      </li>
    {% endif %}
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text|linebreaks }}</p>
  <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a> <br>
  {% if post.group and show_group_link %}
    Группа:
    <a href="{% url 'posts:group_list' post.group.slug %}"> {{ post.group }} </a>
  {% endif %}
</article>

yatube/templates/includes/error_forms.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

yatube/templates/includes/field_forms.html
{% load user_filters %}
{% for field in form %}
  <div class="form-group row my-3">
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
        {% if field.field.required %}
          <span class="required text-danger">*</span>
        {% endif %}
    </label>
    {{ field|addclass:'form-control' }}
      {% if field.help_text %}
        <small
           id="{{ field.id_for_label }}-help"
           class="form-text text-muted"
        >
          {{ field.help_text|safe }}
        </small>
      {% endif %}
  </div>
{% endfor %}

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:author' %} active {% endif %}"
            href="{% url 'about:author' %}"
          >
            Об авторе
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %} active {% endif %}"
             href="{% url 'about:tech' %}"
          >
            Технологии
          </a>
        </li>
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'posts:post_create' %} active {% endif %}"
               href="{% url 'posts:post_create' %}"
            >
              Новая запись
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == 'users:password_change' %} active {% endif %}"
               href="{% url 'users:password_change' %}"
            >
              Изменить пароль
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == 'users:logout' %} active {% endif %}"
               href="{% url 'users:logout' %}"
            >
              Выйти
            </a>
          </li>
          <li class="nav-item navbar-text">
            Пользователь: <a href="{% url 'posts:profile' user.username %}"> {{ user.username }} <a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == 'users:login' %} active {% endif %}"
               href="{% url 'users:login' %}"
            >
              Войти
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == 'users:signup' %} active {% endif %}"
               href="{% url 'users:signup' %}"
            >
              Регистрация
            </a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
</header>
{% endwith %}