yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech')

]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.post_create, name='post_create'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts'))
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import mimetypes

    import debug_toolbar

    mimetypes.add_type("application/javascript", ".js", True)
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    """Класс для таблицы Группы"""

    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    class Meta:
        verbose_name = 'группа'
        verbose_name_plural = 'группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    """Класс для таблицы со всеми постами"""

    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        verbose_name = 'пост'
        verbose_name_plural = 'посты'
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:settings.FIRST_15_SYMBOLS]


class Comment(models.Model):
    """Класс для комментариев"""

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'комментарий'
        verbose_name_plural = 'комментарии'
        ordering = ('-created',)

    def __str__(self):
        return f'{self.author} оставил: {self.text}'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        verbose_name = 'подписка'
        verbose_name_plural = 'подписки'

        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_user_author'
            ),
            models.CheckConstraint(
                check=~models.Q(user=models.F('author')),
                name='check_self_follow'
            ),
        ]

    def __str__(self):
        return f'{self.user} подписан на {self.author}'

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget.attrs['placeholder'] = (
            'Тут обязательно должен быть какой-нибудь текст. '
            'Введи что-нибудь,ну пожалуйста 😥'
        )
        self.fields['group'].empty_label = (
            'Тут можно выбрать группу, если желаете 🙂'
        )

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Введите текст',
            'group': 'Выберите группу'
        }
        help_text = {
            'text': 'Любую абракадабру',
            'group': 'Из уже существующих'
        }


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget.attrs['placeholder'] = (
            'Тут обязательно должен быть какой-нибудь текст. '
            'Оставьте положительный коммент,ну пожалуйста 😥'
        )

    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Введите текст'
        }
        help_text = {
            'text': 'Можно оставить положительный коммент'
        }

yatube/posts/views.py
import contextlib

from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import my_paginator


def index(request):
    """Функция для печати постов (главная страница)"""
    post_list = Post.objects.select_related('author', 'group').all()
    page_obj = my_paginator(request, post_list)
    template = 'posts/index.html'
    context = {
        'page_obj': page_obj
    }
    return render(request, template, context)


def group_posts(request, slug):
    """Функция для печати постов по группам"""
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = my_paginator(request, post_list)
    template = 'posts/group_list.html'
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user,
        author=author
    ).exists()
    post_list = author.posts.all()
    page_obj = my_paginator(request, post_list)
    template = 'posts/profile.html'
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following
    }
    return render(request, template, context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    template = 'posts/post_detail.html'
    context = {
        'post': post,
        'form': form,
        'comments': comments
    }
    return render(request, template, context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if form.is_valid():
        form = form.save(commit=False)
        form.author = request.user
        form.save()
        return redirect('posts:profile', request.user.username)
    template = 'posts/create_post.html'
    context = {'form': form, 'is_edit': False}
    return render(
        request,
        template,
        context
    )


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    template = 'posts/create_post.html'
    context = {'form': form, 'is_edit': True, 'post': post}
    return render(
        request,
        template,
        context
    )


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts_featured_authors = Post.objects.filter(
        author__following__user=request.user
    )
    page_obj = my_paginator(request, posts_featured_authors)
    template = 'posts/follow.html'
    context = {
        'page_obj': page_obj
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    with contextlib.suppress(IntegrityError):
        Follow.objects.get_or_create(
            user=request.user,
            author=author
        )
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактировать пост
          {% else %}
            Новый пост
          {% endif %}
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data" action="
            {% if is_edit %}
              {% url 'posts:post_edit' post.pk %}
            {% else %}
              {% url 'posts:post_create' %}
            {% endif %}">
            {% include 'includes/error_forms.html' %}
            {% csrf_token %}
            {% include 'includes/field_forms.html' %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %} Последние обновления на сайте {% endblock %}
{% block content %}
  <h1> Последние обновления на сайте </h1>
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    {% include 'includes/article.html' with show_group_link=True show_author=True%}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} Записи сообщества {{ group.title }} {% endblock %}
{% block content %}
  <h1> {{ group.title }} </h1>
  <p>
    {{ group.description|linebreaks }}
  </p>
  {% for post in page_obj %}
    {% include 'includes/article.html' with show_author=True %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %} Последние обновления на сайте {% endblock %}
{% load cache %}
{% block content %}
  <h1> Последние обновления на сайте </h1>
  {% include 'posts/includes/switcher.html' %}
  {% cache 20 index_page with page_obj %}
    {% for post in page_obj %}
      {% include 'includes/article.html' with show_group_link=True show_author=True%}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% endcache %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load user_filters %}
{% load thumbnail %}
{% block title %} Пост {{ post|truncatechars:30 }} {% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа:
            <a href="{% url 'posts:group_list' post.group.slug %}">
              {{ post.group }}
            </a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: <b> {{ post.author.get_full_name }} </b>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора:  <span > {{ post.author.posts.count }} </span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p> {{ post.text|linebreaks }} </p>
      {% if request.user == post.author %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
          Редактировать запись
        </a>
      {% endif %}
      {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      {% endif %}
      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="{% url 'posts:profile' comment.author.username %}">
                {{ comment.author.username }}
              </a>
            </h5>
              <p>
               {{ comment.text }}
              </p>
            </div>
          </div>
      {% endfor %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %} Профайл пользователя {{ author.get_full_name }} {% endblock %}
{% block content %}
  <div class="mb-5">
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ author.posts.count }} </h3>
    {% if request.user.username != author.username %}
      {% if following%}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
      {% endif %}
    {% endif %}
  </div>
  {% for post in page_obj %}
    {% include 'includes/article.html' with show_group_link=True %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}